name: Cache Data

on:
  push:
    branches:
      - main

  # schedule:
  #   - cron: "*/5 * * * *"

jobs:
  dumpData:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: cache
          fetch-depth: 1
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: "3.x"

      - working-directory: cache
        name: Install dependencies
        run: pip install -U pip && pip install -r requirements.txt

      - working-directory: cache
        name: Dump Data
        run: python main.py

      - name: Commit changes to cache branch
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add cache/Data
          git commit -m "Auto Dumped Data"

      - name: Force Push changes
        uses: ad-m/github-push-action@master
        with:
          force_with_lease: true
          branch: cache
          github_token: ${{ secrets.GITHUB_TOKEN }}
